//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.23 at 06:12:17 PM CET 
//


package core.com.example;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LaptopSpecification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LaptopSpecification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="screen" type="{example.com}Screen"/&gt;
 *         &lt;element name="touchpad" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="processor" type="{example.com}Processor"/&gt;
 *         &lt;element name="ram" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="space" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="discType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gpu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="gpuRam" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="os" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dvd" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LaptopSpecification", propOrder = {
    "id",
    "name",
    "screen",
    "touchpad",
    "processor",
    "ram",
    "space",
    "discType",
    "gpu",
    "gpuRam",
    "os",
    "dvd"
})
public class LaptopSpecification {

    protected long id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected Screen screen;
    @XmlElement(required = true)
    protected String touchpad;
    @XmlElement(required = true)
    protected Processor processor;
    @XmlElement(required = true)
    protected String ram;
    @XmlElement(required = true)
    protected String space;
    @XmlElement(required = true)
    protected String discType;
    @XmlElement(required = true)
    protected String gpu;
    @XmlElement(required = true)
    protected String gpuRam;
    @XmlElement(required = true)
    protected String os;
    @XmlElement(required = true)
    protected String dvd;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the screen property.
     * 
     * @return
     *     possible object is
     *     {@link Screen }
     *     
     */
    public Screen getScreen() {
        return screen;
    }

    /**
     * Sets the value of the screen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Screen }
     *     
     */
    public void setScreen(Screen value) {
        this.screen = value;
    }

    /**
     * Gets the value of the touchpad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTouchpad() {
        return touchpad;
    }

    /**
     * Sets the value of the touchpad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTouchpad(String value) {
        this.touchpad = value;
    }

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link Processor }
     *     
     */
    public Processor getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Processor }
     *     
     */
    public void setProcessor(Processor value) {
        this.processor = value;
    }

    /**
     * Gets the value of the ram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRam() {
        return ram;
    }

    /**
     * Sets the value of the ram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRam(String value) {
        this.ram = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpace() {
        return space;
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the discType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscType() {
        return discType;
    }

    /**
     * Sets the value of the discType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscType(String value) {
        this.discType = value;
    }

    /**
     * Gets the value of the gpu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpu() {
        return gpu;
    }

    /**
     * Sets the value of the gpu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpu(String value) {
        this.gpu = value;
    }

    /**
     * Gets the value of the gpuRam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpuRam() {
        return gpuRam;
    }

    /**
     * Sets the value of the gpuRam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpuRam(String value) {
        this.gpuRam = value;
    }

    /**
     * Gets the value of the os property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOs() {
        return os;
    }

    /**
     * Sets the value of the os property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOs(String value) {
        this.os = value;
    }

    /**
     * Gets the value of the dvd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDvd() {
        return dvd;
    }

    /**
     * Sets the value of the dvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDvd(String value) {
        this.dvd = value;
    }

}
