//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.23 at 03:44:56 PM CET 
//


package core.com.example;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="laptop" type="{example.com}LaptopSpecification"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "laptop"
})
@XmlRootElement(name = "LaptopResponse")
public class LaptopResponse {

    @XmlElement(required = true)
    protected LaptopSpecification laptop;

    /**
     * Gets the value of the laptop property.
     * 
     * @return
     *     possible object is
     *     {@link LaptopSpecification }
     *     
     */
    public LaptopSpecification getLaptop() {
        return laptop;
    }

    /**
     * Sets the value of the laptop property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaptopSpecification }
     *     
     */
    public void setLaptop(LaptopSpecification value) {
        this.laptop = value;
    }

}
