//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.23 at 02:22:11 PM CET 
//


package core.com.example;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the core.com.example package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: core.com.example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProducerLaptopRequest_0020 }
     * 
     */
    public GetProducerLaptopRequest_0020 createGetProducerLaptopRequest_0020() {
        return new GetProducerLaptopRequest_0020();
    }

    /**
     * Create an instance of {@link GetScreenTypeLaptopRequest_0020 }
     * 
     */
    public GetScreenTypeLaptopRequest_0020 createGetScreenTypeLaptopRequest_0020() {
        return new GetScreenTypeLaptopRequest_0020();
    }

    /**
     * Create an instance of {@link LaptopResponse }
     * 
     */
    public LaptopResponse createLaptopResponse() {
        return new LaptopResponse();
    }

    /**
     * Create an instance of {@link LaptopSpecification }
     * 
     */
    public LaptopSpecification createLaptopSpecification() {
        return new LaptopSpecification();
    }

    /**
     * Create an instance of {@link Screen }
     * 
     */
    public Screen createScreen() {
        return new Screen();
    }

    /**
     * Create an instance of {@link Processor }
     * 
     */
    public Processor createProcessor() {
        return new Processor();
    }

}
