//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.23 at 03:44:56 PM CET 
//


package core.com.example;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProducerLaptopRequest }
     * 
     */
    public com.example.GetProducerLaptopRequest createGetProducerLaptopRequest() {
        return new com.example.GetProducerLaptopRequest();
    }

    /**
     * Create an instance of {@link GetScreenTypeLaptopRequest }
     * 
     */
    public com.example.GetScreenTypeLaptopRequest createGetScreenTypeLaptopRequest() {
        return new com.example.GetScreenTypeLaptopRequest();
    }

    /**
     * Create an instance of {@link LaptopResponse }
     * 
     */
    public com.example.LaptopResponse createLaptopResponse() {
        return new com.example.LaptopResponse();
    }

    /**
     * Create an instance of {@link LaptopSpecification }
     * 
     */
    public com.example.LaptopSpecification createLaptopSpecification() {
        return new com.example.LaptopSpecification();
    }

    /**
     * Create an instance of {@link Screen }
     * 
     */
    public com.example.Screen createScreen() {
        return new com.example.Screen();
    }

    /**
     * Create an instance of {@link Processor }
     * 
     */
    public com.example.Processor createProcessor() {
        return new com.example.Processor();
    }

}
